### ISSUE TITLE
GraphQL query on navigation.html page is not retrieving stripe customer id

### ISSUE THREAD

**Issue by bhargav-codes** [bigcommerce/subscription-foundation#13]
Hello, 
I have enabled subscription foundation but on my account settings, manage subscription link is redirecting to not found and I suspect this because I am receiving null on the response of GraphQL query to get the customer data ... My graphQL query looks like this

 `fetch('/graphql', {
  method: 'POST',
  credentials: 'same-origin',
  headers: {
      'Content-Type': 'application/json',
      'Authorization': 'Bearer {{settings.storefront_api.token}}'
  },
  body: JSON.stringify({ query: query CustomerAttributes {
  customer {
    email
    entityId
    attributes {
        stripe_customer_id: attribute(entityId:1) {
            entityId
            value
      }
    }
  }
}})
})`

The user is actually logged in and the response from this query gives me the following JSON 

`{
    "data": {
        "customer": {
            "email": "testing@example.com",
            "entityId": 12,
            "attributes": {
                "stripe_customer_id": {
                    "entityId": 1,
                    "value": null
                }
            }
        }
    }
}`

I have enabled store credit card from stripe settings on BC and still don't understand why is this issue coming up .... This GraphQL query is from the app support section and still it is having this issue ... Please let me know if there is an alternate way to do it or if I am missing something over here

**Comment by becomevocal** [comment]
@bhargav-codes this is happening because the template had a hardcoded '1' as the entityId. A PR is pending that should resolve this, however you can look up the right ID to put in the "stripe_customer_id" query by doing one of the following things:
- Look in the customerAttributeId column of your app's DB for the store
- Use the BC API to query your created customer attributes
