### ISSUE TITLE
Vercel deployment wants me to enter NEXT_PUBLIC_APP_URL.

### ISSUE THREAD

**Issue by bhargav-codes** [bigcommerce/subscription-foundation#16]
I am trying to deploy subscription foundation on Vercel using the Vercel button, but it needs me to enter the APP URL. I am not sure how can I have an app URL before I actually deploy it ?

**Comment by becomevocal** [comment]
@bhargav-codes that APP URL is used for generating callbacks, which you don't need for the first deployment. The only required variable is the the DATABASE_URL, which is a Postgres URL by default. I recommend using https://supabase.com/ to get a quick DB to test with. You can find you connection string here: https://supabase.com/docs/guides/database/connecting-to-postgres#finding-your-connection-string

Once you paste your connection string into DATABASE_URL in the Vercel deploy screen, set all the rest of the vars to '1234' then deploy. That should successfully deploy. Then you can update the APP_URL to be the one Vercel generates within the first deploy! You'll use that URL in your BC Dev Tools area too, within the callback URLS.

Let me know if this helps.

**Comment by bhargav-codes** [comment]
Hello @becomevocal , thank you so much for the response, it worked perfectly ... I appreciate you help ... 
One more thing, the file https://github.com/bigcommerce/subscription-foundation/blob/main/src/templates/subscribe-and-save-widget.hbs#L84 , line 84 checks only for physical items and not the digital ones ... It should have `item_id: json.lineItems.physicalItems.length == 0 ? json.lineItems.digitalItems[0].id : json.lineItems.physicalItems[0].id` instead of `item_id: json.lineItems.physicalItems[0].id` as it throws error with the digital items when there is no product in the cart .. Thanks

**Comment by bhargav-coding** [comment]
--UPDATE--
I am still facing those issues but anyhow I was able to install my app on my store and connected my stripe account. But when I am trying to continue, I am getting the error as you can see on top right 
<img width="1161" alt="Screen Shot 2022-09-02 at 2 13 07 PM" src="https://user-images.githubusercontent.com/112709569/188213684-07f5cb75-b0ea-47bd-b0fc-9f4b7672cd3c.png">
But when I tried to refresh that page I am getting this error on the app page 
<img width="1463" alt="Screen Shot 2022-09-02 at 2 16 03 PM" src="https://user-images.githubusercontent.com/112709569/188214077-57079c31-bb22-474c-b925-17e1a7f96346.png">

I suspect the error is related to something that is wrong with the database from supabase... Let me know if there is something that I could do to fix this issue .

**Comment by bhargav-coding** [comment]
I found the solution to this problem.
When you are adding DATABASE_URL to the environment variables. Add '?pgbouncer=true' to the end of your postgres URL. 
So the URL will look like this `postgres://postgres:[PASSWORD]@[HOST].supabase.co:6543/postgres?pgbouncer=true`
