### ISSUE TITLE
TypeError: Reflect.getMetadata is not a function

### ISSUE THREAD

**Issue by kesarweb** [bigcommerce/subscription-foundation#21]
The app worked for a few weeks, nothing has been changed, and I am now getting the below error when I go Account -> Manage Subscriptions

Server Error
TypeError: Reflect.getMetadata is not a function

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///var/www/html/stripe_foundations/node_modules/class-transformer/cjs/decorators/type.decorator.js (13:39)
eval
webpack-internal:///(api)/./shared/payloads/product/ProductSubConfigPayload.ts (15:410)
Array.reduce
<anonymous>
_applyDecoratedDescriptor
webpack-internal:///(api)/./shared/payloads/product/ProductSubConfigPayload.ts (15:367)
eval
webpack-internal:///(api)/./shared/payloads/product/ProductSubConfigPayload.ts (43:20)
Object.(api)/./shared/payloads/product/ProductSubConfigPayload.ts
file:///var/www/html/stripe_foundations/.next/server/pages/api/stripe/create-customer-portal-session.js (512:1)
__webpack_require__
file:///var/www/html/stripe_foundations/.next/server/webpack-api-runtime.js (33:42)
eval
webpack-internal:///(api)/./backend/services/bigcommerce/catalog/products.ts (6:106)
Object.(api)/./backend/services/bigcommerce/catalog/products.ts
file:///var/www/html/stripe_foundations/.next/server/pages/api/stripe/create-customer-portal-session.js (312:1)
__webpack_require__
file:///var/www/html/stripe_foundations/.next/server/webpack-api-runtime.js (33:42)

**Comment by huntario** [comment]
Hunter, with BigCommerce here. Thanks for opening up this issue. Taking a look at this, I’m only able to replicate this by starting up the app, clicking the “manage subscriptions” link before Next js has finished compiling the client and server. Please let me know if this continues after the app has been given enough time to startup. The issue may cache, so you’ll want to run npm run dev, and give Next a chance to do its work before starting. If the error remains, please let me know the following from your terminal:

`node -v `

`nvm ls`

`npm run dev `and the output you see in your terminal while encountering the error. 

Hopefully this helps. Please let me know if this continues to block your work.
