### ISSUE TITLE
Database error when installing an app with a free postgres DB mentioned in the documentation - cannot use free postgres

### ISSUE THREAD

**Issue by kesarweb** [bigcommerce/subscription-foundation#23]
Error: Database error
Error querying the database: db error: ERROR: canceling statement due to statement timeout
   0: sql_migration_connector::flavour::postgres::sql_schema_from_migration_history
             at migration-engine/connectors/sql-migration-connector/src/flavour/postgres.rs:375
   1: migration_core::api::DevDiagnostic
             at migration-engine/core/src/api.rs:89

**Comment by huntario** [comment]
Hunter, with BigCommerce here again. 

When you say “a free postgres DB mentioned in the documentation” do you mean Supbase - https://supabase.com/ ? Mentioned here - https://developer.bigcommerce.com/api-docs/partner/subscription-solutions/foundation-guide#run-migration-and-start-the-server ?

I’ve run through the setup process and was not able to replicate this issue. Can you confirm if you were using Supbase or another database service? Was there a specific command in the terminal that replicates this issue?

**Comment by huntario** [comment]
Happy to take another look at this if we can get that info.
