### ISSUE TITLE
Account -> Manage Subscriptions link goes to an app error

### ISSUE THREAD

**Issue by kesarweb** [bigcommerce/subscription-foundation#26]
{"name":"Error","status":422,"message":"Request returned error code: 422 and body: {\"status\":422,\"title\":\"Query parameter \\\"id:in\\\" value may contain only integer values. For input string: \\\"undefined\\\".\",\"type\":\"https://developer.bigcommerce.com/api-docs/getting-started/api-status-codes\",\"errors\":{}}","trace":"Error: Request returned error code: 422 and body: {\"status\":422,\"title\":\"Query parameter \\\"id:in\\\" value may contain only integer values. For input string: \\\"undefined\\\".\",\"type\":\"https://developer.bigcommerce.com/api-docs/getting-started/api-status-codes\",\"errors\":{}}\n    at Gunzip.cb (/var/www/html/stripe_foundations/node_modules/node-bigcommerce/lib/request.js:119:31)\n    at Gunzip.zlibBufferOnEnd (zlib.js:152:10)\n    at Gunzip.emit (events.js:376:20)\n    at Gunzip.emit (domain.js:470:12)\n    at endReadableNT (internal/streams/readable.js:1336:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)","timestamp":"2023-01-13T06:52:20.603Z"}

This is due to variable translation issue - does not look like
// BigCommerce Customer Attribute Field & Metafield Names
export const SUBSCRIPTION_CUSTOMER_ATTRIBUTE_NAME = "stripe_customer_id";
export const SUBSCRIPTION_IDS_ATTRIBUTE_NAME = "stripe_subscription_ids";
export const SUBSCRIPTION_METAFIELD_KEY = "subscription_config";
export const SUBSCRIPTION_METAFIELD_NAMESPACE = "Stripe Billing";

are properly being translated to the working code.

**Comment by kesarweb** [comment]
store hash for the reference zeiyemdcjo

**Comment by huntario** [comment]
Thanks for noting this issue. This should be fixed by the above PR.
