### ISSUE TITLE
stripe customer ID is hardcoded to 1

### ISSUE THREAD

**Issue by kesarweb** [bigcommerce/subscription-foundation#27]
![image](https://user-images.githubusercontent.com/4732537/215915791-ed8d26f5-19b9-4939-a63a-4c4413adbc7f.png)

**Comment by huntario** [comment]
Hunter, with BigCommerce here again.

The BigCommerce APIs have an entity called Customer Attributes - https://developer.bigcommerce.com/docs/rest-management/customers/customer-attributes#get-all-customer-attributes

The attribute keys are recorded separate from the customer. These keys can then be assigned specific values for a specific customer. When the app installs, it will create a customer attribute. This attribute will have a storewide ID, and each customer will have a unique value. 

This storewide attribute ID is stored in the store’s row within the Store table. See the screenshot to see how this value is then placed within the script. This will not always be 1, but will be the ID of the customer attribute created on installation.  

<img width="3056" alt="Screenshot 2023-06-28 at 8 53 07 PM" src="https://github.com/bigcommerce/subscription-foundation/assets/5630999/5f864aa2-0514-47ff-a5c2-c673c5e502a3">
